# Generated by Django 2.2.5 on 2020-08-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=75)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('starttimestamp', models.TimeField()),
                ('endtimestamp', models.TimeField()),
                ('ac_starttimestamp', models.TimeField(blank=True, null=True)),
                ('ac_endtimestamp', models.TimeField(blank=True, null=True)),
                ('projecttitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker.ProjectMaster')),
            ],
        ),
    ]
